export default {
  SET_PLAYER_SHOW: 'SET_PLAYER_SHOW',
  SET_CURRENT_SONG: 'SET_CURRENT_SONG',
  SET_PLAYING_STATE: 'SET_PLAYING_STATE',
  SET_PLAY_HISTORY: 'SET_PLAY_HISTORY',
  CLEAR_CURRENT_SONG: 'CLEAR_CURRENT_SONG',
  SET_CURRENT_TIME: 'SET_CURRENT_TIME',
  SET_PLAYLIST: 'SET_PLAYLIST',
  SET_USER: 'SET_USER',
  SET_USER_PLAYLIST: 'SET_USER_PLAYLIST'
}
